server:
  port: 9000

spring:
  application:
    name: game-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/hat
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
#    hikari:
#      schema: game

app:
  game:
    max-players: 8