server:
  port: 9000

spring:
  application:
    name: game-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${APP_HOST:localhost}:${DB_PORT:5402}/hat_game
    username: ${DB_USER:hat_game}
    password: ${DB_PASSWORD:test1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: game
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  game:
    max-players: 8
